[server]
port="3002"
readTimeout=5
writeTimeout=5
closeTimeout=5

[logger]
file="log.log"

[zipkin]
isEnable=false
host="127.0.0.1"
port="9411"

[database]
type="mysql"
host="127.0.0.1"
dbName="godb"
userName="root"
password="root"
connectionString="root:root@/godb?charset=utf8&parseTime=True&loc=Local"

[cache]
type="redis"
host="localhost"
port="6379"
password=""

[mq]
type="sqs"
queueUrl=""
visibilityTimeout=30
region="us-east-1"
accessKey=""
secret=""
